spring.application.name=KPMG-ONGC

server.port=11000
spring.datasource.url=jdbc:postgresql://172.16.32.168:5432/ongc_poc?currentSchema=ongc_policy_rep
spring.datasource.username=ongc_user
spring.datasource.password=ongc_poc_2024
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true

server.servlet.context-path=/ongc

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

secret.key=afafasfafafasfasfasfafacasdasfasxASFACASDFACASDFASFASFDAFASFASDAADSCSDFADCVSGCFVADXCcadwavfsfarvf